services:
  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    env_file:
      - ../main.env
    volumes:
      - ./opt/postgres_data:/var/lib/postgresql/data
      - ./pgvector/init.sql:/docker-entrypoint-initdb.d/init.sql

  broker:
    image: apache/kafka:latest
    container_name: broker
    env_file:
      - kafka/kafka.env
    volumes:
      - ./kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    ports:
      - "29092:29092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - broker
    env_file:
      - kafka/kafkaui.env
    ports:
      - "8080:8080"